#!/bin/bash

exec >/dev/null
exec 2>/dev/null

cp -a external/cobbler cobbler
cd cobbler && find .git -type d | grep remotes | xargs rm -rf
git branch -r -d origin/master
git branch -r -d origin/devel
